### ISSUE TITLE
Workshop Collection

### ISSUE THREAD

**Issue by Snavellet** [Hackebein/docker-garrysmod#6]
The server works without workshop collection, but the opposite isn't working.

**Comment by Hackebein** [comment]
I'm using it every day with a workshop collection and it's working nice for me. (As written down for 'Example for TTT')

Can you please provide more information?

**Comment by Snavellet** [comment]
These are the screenshots for my Docker Compose configuration file, Digital Ocean droplet specification, my UFW firewall setup, and the logs of the dedicated server which had stopped there. Relating to the logs, it doesn't say "VAC Secure Mode Enabled" or something similar like that as the last log which source dedicated servers should show. When I try to join, it said "Connection Failed After 6 Retries", but without a workshop collection, it works.

![compose-gmod](https://user-images.githubusercontent.com/51810664/82978085-e0843080-a00d-11ea-9207-142de1822dbe.PNG)
![droplet-specification](https://user-images.githubusercontent.com/51810664/82978087-e11cc700-a00d-11ea-91ac-d38b999c6ff5.PNG)
![Capture](https://user-images.githubusercontent.com/51810664/82978138-04e00d00-a00e-11ea-912a-02a81b23815f.PNG)
![Capture](https://user-images.githubusercontent.com/51810664/82978523-ffcf8d80-a00e-11ea-8b26-05bff8a5603e.PNG)
**with workshop collection**

**Comment by Hackebein** [comment]
That log is incomplete because you missed to add "-it" in your compose file. You need to add this:
```
    stdin_open: true
    tty: true
```

I see your TTT Collection (https://steamcommunity.com/sharedfiles/filedetails/?id=2073568192) is huge. I think the missing part in the log will show us that the server is working as expected and downloading all the workshop content.

Hint: You can but you don't need to specify GLST by your self. The Container is generating GLST for the server if you provide an AUTHKEY. As described in docs `If you have activated the API (with AUTHKEY), this step happens automatically.`

Greetings to Singapore

**Comment by Snavellet** [comment]
Hello, I see the logs now, it is downloading the addons from the collection as you mentioned, so I presume it is working, thank you and have a good day.
